name: chat_app_ex
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.1.1
  drift: ^2.27.0
  firebase_messaging: ^15.2.7
  firebase_core: ^3.14.0
  qr_flutter: ^4.1.0
  google_maps_flutter: ^2.12.3
  google_maps_flutter_ios: ^2.15.4
  location: ^8.0.1
  firebase_auth: ^5.6.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  shared_preferences: ^2.5.3
  sqlite3_flutter_libs: ^0.5.34
  path_provider: ^2.1.5
  path: ^1.9.1
  responsive_builder: ^0.7.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  go_router: ^15.2.4
  http: ^1.1.0
  cloud_firestore: ^5.6.9
  flutter_form_builder: ^10.0.1
  form_builder_validators: ^11.2.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  google_fonts: ^6.2.1
  flutter_screenutil: ^5.9.3
  googleapis_auth: ^2.0.0
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  injectable_generator: ^2.7.0
  drift_dev: ^2.27.0
  freezed: ^3.0.6
  json_serializable: ^6.9.5
  build_runner: ^2.4.9
  go_router_builder: ^3.0.0

dependency_overrides:
  # Waiting for https://github.com/Lyokone/flutterlocation/issues/1031
  location_web:
    git:
      url: https://github.com/Lyokone/flutterlocation
      path: packages/location_web
      ref: location-v8.0.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/map_style.json
