// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMIDo5fASq3thW-8cLV35e_FaCg0IZsmU',
    appId: '1:450034966670:web:2a9f4760390836881ce9df',
    messagingSenderId: '450034966670',
    projectId: 'chat-app-9b6b5',
    authDomain: 'chat-app-9b6b5.firebaseapp.com',
    storageBucket: 'chat-app-9b6b5.firebasestorage.app',
    measurementId: 'G-41RY50P9H1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoZuZE09MSAgU5KMuldwIcSKgnWCHm3no',
    appId: '1:450034966670:android:b82df28255b4436c1ce9df',
    messagingSenderId: '450034966670',
    projectId: 'chat-app-9b6b5',
    storageBucket: 'chat-app-9b6b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeDfrplVULiSB1kMJpa69LwbSdvDGgJy8',
    appId: '1:450034966670:ios:68f576f705c7f5501ce9df',
    messagingSenderId: '450034966670',
    projectId: 'chat-app-9b6b5',
    storageBucket: 'chat-app-9b6b5.firebasestorage.app',
    iosBundleId: 'com.example.chatAppEx',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeDfrplVULiSB1kMJpa69LwbSdvDGgJy8',
    appId: '1:450034966670:ios:68f576f705c7f5501ce9df',
    messagingSenderId: '450034966670',
    projectId: 'chat-app-9b6b5',
    storageBucket: 'chat-app-9b6b5.firebasestorage.app',
    iosBundleId: 'com.example.chatAppEx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMIDo5fASq3thW-8cLV35e_FaCg0IZsmU',
    appId: '1:450034966670:web:6221f202649e9a231ce9df',
    messagingSenderId: '450034966670',
    projectId: 'chat-app-9b6b5',
    authDomain: 'chat-app-9b6b5.firebaseapp.com',
    storageBucket: 'chat-app-9b6b5.firebasestorage.app',
    measurementId: 'G-XBE6VFDVM6',
  );
}
